spring:
  application:
    name: workplace-booking
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    #Следующие настройки только для gmail-адресов
    properties:
      mail:
        smtp:
          auth: ${ENABLE_EMAIL:false}
          starttls:
            enable: ${ENABLE_EMAIL:false}

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health,info,prometheus,loggers
jwt:
  secret: ${SECRET_KEY:=====================================SecretnyiSecret================================}
  expiration: ${EXPIRATION_TIME:86400000}

email:
  subject-line: ${EMAIL_SUBJECT_LINE:Ваш пароль для входа в систему}
  message-body: ${EMAIL_MESSAGE_BODY:Добрый день! Используйте этот пароль для входа в систему:}
  enable: ${ENABLE_EMAIL:false}

password:
  user-pass: ${USER_PASSWORD:password}