DATABASE_URL: postgresql://localhost:5432/workplace-booking-db
DATABASE_USER: workplace-booking
DATABASE_PASSWORD: workplace-booking

MAIL_HOST: smtp.gmail.com
MAIL_USERNAME: staccato013@gmail.com
MAIL_PASSWORD: "yubx mmvl ymwa miip"
MAIL_PORT: 587

ENABLE_EMAIL: false

SECRET_KEY: =====================================SecretnyiSecret================================
EXPIRATION_TIME: 86400000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
